# Railway configuration for WeasyPrint dependencies
[providers]
python = "3.12"

[phases.setup]
nixPkgs = [
    "cairo",
    "pango",
    "gdk-pixbuf",
    "libffi",
    "shared-mime-info",
    "glib",
    "gtk3",
    "gobject-introspection",
    "fontconfig",
    "freetype",
    "harfbuzz",
    "fribidi",
    "pkg-config",
    "gettext"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn condominio_app.wsgi --bind 0.0.0.0:$PORT"