# Generated by Django 4.2.10 on 2025-04-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACCESOS', 'Accesos'), ('RESIDENTES', 'Residentes'), ('VIVIENDAS', 'Viviendas'), ('FINANCIERO', 'Financiero')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
            ],
        ),
    ]
