# Generated by Django 4.2.10 on 2025-04-30 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACCESOS', 'Accesos'), ('RESIDENTES', 'Residentes'), ('VIVIENDAS', 'Viviendas'), ('FINANCIERO', 'Financiero'), ('PERSONAL', 'Personal')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('filtros', models.JSONField(blank=True, default=dict, help_text='Filtros adicionales en formato JSON')),
                ('formato_preferido', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('HTML', 'HTML para visualización')], default='HTML', max_length=10)),
                ('es_favorito', models.BooleanField(default=False, help_text='Marcar como reporte favorito para acceso rápido')),
                ('ultima_generacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
