# Generated by Django 4.2.10 on 2025-04-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('es_propietario', models.BooleanField(default=False, help_text='Indica si este tipo de residente tiene derechos de propiedad sobre la vivienda')),
            ],
        ),
        migrations.AddField(
            model_name='residente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el residente actualmente vive o está relacionado con la vivienda'),
        ),
        migrations.AddField(
            model_name='residente',
            name='tipo_residente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='viviendas.tiporesidente'),
        ),
        migrations.RunSQL(
            """
            -- Insertar los tipos de residentes predefinidos
            INSERT INTO viviendas_tiporesidente (nombre, descripcion, es_propietario)
            VALUES 
                ('Titular', 'Habitante principal de la vivienda', true),
                ('Dueño', 'Propietario que no reside en el condominio', true),
                ('Copropietario', 'Habitante de la vivienda sin ser titular', true),
                ('Menor', 'Habitante menor de edad', false);
            
            -- Actualizar residentes existentes
            UPDATE viviendas_residente 
            SET tipo_residente_id = (
                SELECT id FROM viviendas_tiporesidente 
                WHERE nombre = CASE 
                    WHEN es_propietario = true THEN 'Titular' 
                    ELSE 'Copropietario' 
                END
                LIMIT 1
            );
            """
        ),
        migrations.AlterField(
            model_name='residente',
            name='tipo_residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='viviendas.tiporesidente'),
        ),
    ]