# Generated by Django 4.2.10 on 2025-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el edificio está activo o ha sido dado de baja'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha en la que se dio de baja el edificio', null=True),
        ),
        migrations.AddField(
            model_name='edificio',
            name='motivo_baja',
            field=models.TextField(blank=True, help_text='Motivo por el cual se dio de baja el edificio', null=True),
        ),
    ]
