# Generated by Django 4.2.10 on 2025-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_add_tipo_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la vivienda está activa o ha sido dada de baja'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha en la que se dio de baja la vivienda', null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='motivo_baja',
            field=models.TextField(blank=True, help_text='Motivo por el cual se dio de baja la vivienda', null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='estado',
            field=models.CharField(choices=[('OCUPADO', 'Ocupado'), ('DESOCUPADO', 'Desocupado'), ('MANTENIMIENTO', 'En mantenimiento'), ('BAJA', 'Dado de baja')], default='DESOCUPADO', max_length=15),
        ),
    ]